name: exfiltrate_background
on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run some in-tree code
        run: |
          cd exfiltrate_background
          cargo run
      - name: do something with secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          sleep 5
